### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by Kengkat** [gongpha/pscp-python-project-2022#8]
### File
- Releases: 1.0.0 (db499c64ceba2cf0d53b021880e3a6eeda46805e)
- File: pscp-project-2022-x11-64.7z

### System Spec.
- OS: Devuan GNU/Linux 4 (chimaera) x86_64
- Kernel: 5.10.0-9-amd64

### What Happened
*Opens the `pscp` binary with non-root user on terminal*
Loading screen shows up
Finishes loading
Menu screen shows up
*Clicks `Open Python Interactive Console`*
Some kind of console shows up
*Types `c` to the console*
**`Segmentation fault` and gets kick out to terminal**

### Output
```
Godot Engine v3.5.1.stable.official.6fed1ffa3 - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD OLAND (DRM 2.50.0, 5.10.0-9-amd64, LLVM 11.0.1)
Async. shader compilation: OFF

Pythonscript 0.50.0 (CPython 3.8.5.final.0)
ERROR: Failed to retrieve non-existent singleton 'VisualScriptEditor'.
   at: get_singleton_object (core/engine.cpp:201)
Cannot retreive singleton VisualScriptEditor
Segmentation fault
```

**Comment by gongpha** [comment]
seckfoalt

**Comment by gongpha** [comment]
Maybe the issue from [the plugin](https://github.com/touilleMan/godot-python) causes a seckfoalt. Better to wait for [their new refactoring](https://github.com/touilleMan/godot-python/tree/godot4-meson) for Godot 4 or rewrite all Python works to GDScript. (Or C++ if our collaborators prefer. But it can cause more seckfoalt than this plugin lmao)

**Comment by gongpha** [comment]
The collaborators were bored with their old works. andd yes, me too.

And I'm also tired of waiting for the update.

will go to your house later and fix it with a sledgehammer.

EDIT : he's gone
